name: Build Workflow
run-name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 31
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Get compatible Maven
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvf apache-maven-3.9.6-bin.tar.gz -C /opt && rm apache-maven-3.9.6-bin.tar.gz
          export M2_HOME=/opt/maven
          export MAVEN_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}
      - name: checkout cloudbeaver
        run: |
          mkdir ~/build && cd ~/build
          git clone https://github.com/dbeaver/cloudbeaver.git -b release_24_2_1 ~/build/cloudbeaver
          git clone https://github.com/dbeaver/dbeaver.git -b release_24_2_1 ~/build/dbeaver
          git clone https://github.com/dbeaver/dbeaver-common.git -b release_24_2_1 ~/build/dbeaver-common
      - name: Compiling Cloudbeaver
        run: |
          cd ~/build/cloudbeaver/deploy && ./build.sh
          rm -rf ~/build/cloudbeaver/webapp
          rm -rf ~/build/cloudbeaver/server
