name: Build Workflow
run-name: build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      M2_HOME: /opt/maven
      MVN_HOME: /opt/maven
      MAVEN_HOME: /opt/maven
    steps:
      - uses: actions/checkout@v4
      - uses: EthanSK/git-branch-name-action@v1
      - run: echo $GIT_BRANCH_NAME
      - uses: actions/setup-node@v4
        with:
          node_version: 31
      - name: Get Yarn and compatible Maven
        run: |
          curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install -y openjdk-17-jdk yarn nodejs
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvf apache-maven-3.9.6-bin.tar.gz -C /opt && rm apache-maven-3.9.6-bin.tar.gz
          ln -s /opt/apache-maven-3.9.6 /opt/maven

          env
          mvn -v
      - name: checkout cloudbeaver
        run: |
          mkdir ~/build && cd ~/build
          git clone https://github.com/dbeaver/cloudbeaver.git -b release_24_2_1 ~/build/cloudbeaver
          git clone https://github.com/dbeaver/dbeaver.git -b release_24_2_1 ~/build/dbeaver
          git clone https://github.com/dbeaver/dbeaver-common.git -b release_24_2_1 ~/build/dbeaver-common
      - name: Compiling Cloudbeaver
        run: |
          export PATH=${M2_HOME}/bin:${PATH}
          cd ~/build/cloudbeaver/deploy && ./build.sh

          rm -rf ~/build/cloudbeaver/webapp
          rm -rf ~/build/cloudbeaver/server
      - name: Generating artifact
        run: |
          cd ~/build
          rm -rf cloudbeaver/.git
          tar -cvz -f ./cloudbeaver.tar.gz cloudbeaver
          chmod 777 ./cloudbeaver.tar.gz
          cd /home/runner
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            ./build/cloudbeaver.tar.gz
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}