name: Build Workflow
run-name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      M2_HOME: /opt/maven
      MAVEN_HOME: /opt/maven
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 31
      - name: Get compatible Maven
        run: |
          apt update && apt install -y openjdk-17-jdk yarn nodejs
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvf apache-maven-3.9.6-bin.tar.gz -C /opt && rm apache-maven-3.9.6-bin.tar.gz
      - name: checkout cloudbeaver
        run: |
          env
          mkdir ~/build && cd ~/build
          git clone https://github.com/dbeaver/cloudbeaver.git -b release_24_2_1 ~/build/cloudbeaver
          git clone https://github.com/dbeaver/dbeaver.git -b release_24_2_1 ~/build/dbeaver
          git clone https://github.com/dbeaver/dbeaver-common.git -b release_24_2_1 ~/build/dbeaver-common
      - name: Compiling Cloudbeaver
        run: |
          export PATH=${M2_HOME}/bin:${PATH}
          cd ~/build/cloudbeaver/deploy && ./build.sh
          rm -rf ~/build/cloudbeaver/webapp
          rm -rf ~/build/cloudbeaver/server
