name: Build Workflow
run-name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: 31
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: checkout cloudbeaver
        run: |
          mkdir ~/build && cd ~/build
          git clone https://github.com/dbeaver/cloudbeaver.git -b release_24_2_1 ~/build/cloudbeaver
          git clone https://github.com/dbeaver/dbeaver.git -b release_24_2_1 ~/build/dbeaver
          git clone https://github.com/dbeaver/dbeaver-common.git -b release_24_2_1 ~/build/dbeaver-common
      - name: Compiling Cloudbeaver
        run: |
          ls -lh ~/build
          cd ~/build/cloudbeaver/deploy && ./build.sh
